# Generated by Django 4.1.3 on 2022-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('volume', models.FloatField()),
                ('largura', models.FloatField()),
                ('comprimento', models.FloatField()),
                ('altura', models.FloatField()),
                ('qtd_total', models.IntegerField()),
                ('qtd_pane', models.IntegerField()),
                ('qtd_aplicada', models.IntegerField()),
                ('observacoes', models.TextField()),
                ('data_atualizacao', models.DateField()),
            ],
        ),
    ]
