# Generated by Django 4.1.3 on 2022-11-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.categoria'),
            preserve_default=False,
        ),
    ]
