# Generated by Django 4.1.3 on 2022-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_categoria_equipamento_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esquadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('1GCC', 'Mestre'), ('1/1GCC', 'Profeta'), ('2/1GCC', 'Aranha'), ('3/1GCC', 'Morcego'), ('4/1GCC', 'Mangrulho'), ('5/1GCC', 'Zagal')], max_length=6)),
            ],
        ),
    ]
