# Generated by Django 4.1.3 on 2022-11-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_esquadrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquadrao',
            name='nome',
            field=models.CharField(choices=[('mestre', '1GCC'), ('profeta', '1/1GCC'), ('aranha', '2/1GCC'), ('morcego', '3/1GCC'), ('mangrulho', '4/1GCC'), ('zagal', '5/1GCC')], max_length=15),
        ),
    ]
