# Generated by Django 4.1.3 on 2022-11-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_remove_esquadrao_link_alter_esquadrao_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='esquadrao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.esquadrao'),
            preserve_default=False,
        ),
    ]
